/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    regions: Region;
    'building-lines': BuildingLine;
    'building-models': BuildingModel;
    'furniture-packages': FurniturePackage;
    quotes: Quote;
    images: Image;
    models: Model;
    textures: Texture;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    regions: RegionsSelect<false> | RegionsSelect<true>;
    'building-lines': BuildingLinesSelect<false> | BuildingLinesSelect<true>;
    'building-models': BuildingModelsSelect<false> | BuildingModelsSelect<true>;
    'furniture-packages': FurniturePackagesSelect<false> | FurniturePackagesSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    images: ImagesSelect<false> | ImagesSelect<true>;
    models: ModelsSelect<false> | ModelsSelect<true>;
    textures: TexturesSelect<false> | TexturesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'integration-settings': IntegrationSetting;
    'quiz-settings': QuizSetting;
    'display-settings': DisplaySetting;
  };
  globalsSelect: {
    'integration-settings': IntegrationSettingsSelect<false> | IntegrationSettingsSelect<true>;
    'quiz-settings': QuizSettingsSelect<false> | QuizSettingsSelect<true>;
    'display-settings': DisplaySettingsSelect<false> | DisplaySettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Sales regions. Models, lines and packages are filtered by these.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions".
 */
export interface Region {
  id: number;
  name: string;
  /**
   * Short region code used in URLs and integrations, e.g. "us".
   */
  code: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Product lines (e.g. BOXXPlex, EDUPlex, Mobile Office) and their sizing rules.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "building-lines".
 */
export interface BuildingLine {
  id: number;
  name: string;
  /**
   * Used in configurator URLs, e.g. ?building=boxxplex.
   */
  slug: string;
  /**
   * What the customer-facing unit count means for this line.
   */
  unitLabel: 'offices' | 'classrooms';
  description?: string | null;
  /**
   * Regulatory thresholds for this line. The largest size on offer is not set here — it is read from the published Building Models.
   */
  rules?: {
    /**
     * Unit count at which restrooms become mandatory. Leave empty if never mandatory.
     */
    restroomsRequiredAt?: number | null;
    /**
     * Unit count at which a second restroom set is required. Leave empty if never.
     */
    secondRestroomSetAt?: number | null;
  };
  regions?: (number | Region)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * One entry per building size. Rooms, roof volumes and cameras are set up visually in the Scene Editor tab.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "building-models".
 */
export interface BuildingModel {
  id: number;
  title: string;
  line: number | BuildingLine;
  /**
   * Number of offices/classrooms this size provides.
   */
  unitCount: number;
  restroomCount?: number | null;
  /**
   * Overall size of the building. Rooms carry their own floor area and will not add up to this — walls, corridors and plant are not in any room.
   */
  sqft?: number | null;
  /**
   * The same size in m². Fill in only if it should not be the conversion of the figure beside it.
   */
  sqm?: number | null;
  /**
   * Display size, e.g. 24' x 56'.
   */
  dimensions?: string | null;
  /**
   * The same, in metres — e.g. 7.3 m × 17.1 m. Free text cannot be converted, so a visitor reading metres sees this or nothing.
   */
  dimensionsMetric?: string | null;
  /**
   * Estimated people. Left empty it is not shown.
   */
  occupancy?: number | null;
  /**
   * Indicative price in USD, shown to the visitor. Left empty it is not shown.
   */
  estimatedPrice?: number | null;
  /**
   * Free text — "8–10 weeks" is not a number.
   */
  leadTime?: string | null;
  model: number | Model;
  thumbnail?: (number | null) | Image;
  regions?: (number | Region)[] | null;
  /**
   * Viewer setup — edited visually in the Scene Editor.
   */
  sceneConfig?: {
    /**
     * Where the visitor lands, and how far they may orbit or zoom.
     */
    camera?: {
      position?: {
        x?: number | null;
        y?: number | null;
        z?: number | null;
      };
      target?: {
        x?: number | null;
        y?: number | null;
        z?: number | null;
      };
      fov?: number | null;
      minDistance?: number | null;
      maxDistance?: number | null;
      minPolarDeg?: number | null;
      maxPolarDeg?: number | null;
    };
    /**
     * Building-level roof volumes. Hidden in the client overview (toggleable).
     */
    roofBlocks?:
      | {
          min: {
            x: number;
            y: number;
            z: number;
          };
          max: {
            x: number;
            y: number;
            z: number;
          };
          id?: string | null;
        }[]
      | null;
    /**
     * Walkable level rooms are drawn at while the building has no storeys. Each storey below carries its own instead.
     */
    floorY?: number | null;
    /**
     * Storeys of a multi-storey building. Each one is the volume that stays visible when the visitor picks it — everything outside is hidden. The visitor only gets a picker once there are two, so a single-storey building needs none of this.
     */
    floors?:
      | {
          key: string;
          name: string;
          /**
           * Walkable level of this storey — where rooms drawn on it start, and what furniture stands on.
           */
          floorY?: number | null;
          box: {
            min: {
              x: number;
              y: number;
              z: number;
            };
            max: {
              x: number;
              y: number;
              z: number;
            };
          };
          id?: string | null;
        }[]
      | null;
    /**
     * A roof supplied as its own model. Placed visually in the Scene Editor.
     */
    roofModel?: {
      model?: (number | null) | Model;
      position?: {
        x?: number | null;
        y?: number | null;
        z?: number | null;
      };
      yawDeg?: number | null;
      scale?: number | null;
    };
    /**
     * Objects hidden in the Scene Editor. Edited visually.
     */
    hiddenNodePaths?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Rooms/zones of the building — edited visually in the Scene Editor.
   */
  rooms?:
    | {
        key: string;
        name: string;
        roomType: 'office' | 'classroom' | 'conference' | 'kitchen' | 'restroom' | 'lounge' | 'hallway' | 'other';
        /**
         * Floor area in ft². Empty means it is worked out from the outline below — fill it in only when you have a better figure than the trace.
         */
        areaSqFt?: number | null;
        /**
         * The same area in m². Empty means the outline, or a conversion of the figure beside it if that one was filled in.
         */
        areaSqM?: number | null;
        /**
         * Floor outline points (XZ plane, meters), drawn in the editor. Each point owns the edge that starts at it, and that edge belongs to one of the four walls.
         */
        floorPolygon?:
          | {
              x: number;
              z: number;
              side?: ('w1' | 'w2' | 'w3' | 'w4') | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Parts of this room with a use of their own — a conference half and a kitchen half with no partition between them. Cut in the Scene Editor. Empty means the room is one space.
         */
        zones?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * The focused-room view is generated from these numbers — the building glb is never cut.
         */
        shell?: {
          /**
           * Walkable floor level. Furniture stands on this plane.
           */
          floorY?: number | null;
          wallHeight?: number | null;
          wallThickness?: number | null;
          floorThickness?: number | null;
          ceilingThickness?: number | null;
          /**
           * Compass point the sun is on. Windows in walls facing it throw daylight in. Leave empty to put the sun outside whichever wall has the most glass.
           */
          sunDirection?: ('n' | 'ne' | 'e' | 'se' | 's' | 'sw' | 'w' | 'nw') | null;
          /**
           * Outward direction per wall. Set from the editor.
           */
          sideAxes?:
            | {
                [k: string]: unknown;
              }
            | unknown[]
            | string
            | number
            | boolean
            | null;
        };
        /**
         * Doors and windows per wall — placed in the Scene Editor.
         */
        openings?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        /**
         * Textures applied to the generated room.
         */
        surfaces?: {
          wallInner?: {
            texture?: (number | null) | Texture;
            /**
             * Meters covered by one horizontal repeat.
             */
            tileWidth?: number | null;
            /**
             * Meters covered by one vertical repeat.
             */
            tileHeight?: number | null;
          };
          floor?: {
            texture?: (number | null) | Texture;
            /**
             * Meters covered by one horizontal repeat.
             */
            tileWidth?: number | null;
            /**
             * Meters covered by one vertical repeat.
             */
            tileHeight?: number | null;
          };
          ceiling?: {
            texture?: (number | null) | Texture;
            /**
             * Meters covered by one horizontal repeat.
             */
            tileWidth?: number | null;
            /**
             * Meters covered by one vertical repeat.
             */
            tileHeight?: number | null;
          };
        };
        /**
         * Real 3D doors and windows. Assign one and it replaces the flat leaf for every opening of that kind in this room.
         */
        openingModels?: {
          door?: {
            model?: (number | null) | Model;
            /**
             * How the model is sized into the opening.
             */
            fit?: ('stretch' | 'contain' | 'none') | null;
            /**
             * Turn the source model so its front faces out of the room.
             */
            yawDeg?: number | null;
            /**
             * Metres from the middle of the wall, + is outward.
             */
            depth?: number | null;
          };
          window?: {
            model?: (number | null) | Model;
            /**
             * How the model is sized into the opening.
             */
            fit?: ('stretch' | 'contain' | 'none') | null;
            /**
             * Turn the source model so its front faces out of the room.
             */
            yawDeg?: number | null;
            /**
             * Metres from the middle of the wall, + is outward.
             */
            depth?: number | null;
          };
        };
        /**
         * Camera fly-to when this room is focused.
         */
        cameraPreset?: {
          position?: {
            x?: number | null;
            y?: number | null;
            z?: number | null;
          };
          target?: {
            x?: number | null;
            y?: number | null;
            z?: number | null;
          };
        };
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Source 3D models, optimized for web delivery automatically on upload. One file only: a .glb, or a .gltf with nothing outside it. A .gltf that keeps its .bin and textures/ as separate files has to be packed first — run `pnpm optimize:model <file.gltf>` and upload the .glb it writes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models".
 */
export interface Model {
  id: number;
  title: string;
  /**
   * Filled automatically during upload optimization.
   */
  meta?: {
    sizeBefore?: number | null;
    sizeAfter?: number | null;
    triangles?: number | null;
    meshes?: number | null;
    materials?: number | null;
    textures?: number | null;
    bboxMin?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    bboxMax?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Photos and thumbnails shown in the configurator UI.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "images".
 */
export interface Image {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Tileable surface textures (walls, floors, ceilings, doors, windows). Re-encoded to webp and capped at 2048px on upload.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "textures".
 */
export interface Texture {
  id: number;
  /**
   * Optional label; the filename is used when empty.
   */
  title?: string | null;
  /**
   * Filled automatically during upload.
   */
  meta?: {
    width?: number | null;
    height?: number | null;
    sizeBefore?: number | null;
    sizeAfter?: number | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {};
}
/**
 * Furniture packages placed as whole groups. Compatibility controls where they are offered.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "furniture-packages".
 */
export interface FurniturePackage {
  id: number;
  title: string;
  family: 'office' | 'conference' | 'kitchen' | 'seating' | 'other';
  tier: 'core' | 'plus';
  model: number | Model;
  thumbnail?: (number | null) | Image;
  /**
   * USD.
   */
  price?: number | null;
  description?: string | null;
  /**
   * Occupied floor rectangle (meters) — used for fit and collision checks. Measured from the model on save; leave blank unless the model needs a smaller or larger one than its bounding box.
   */
  footprint?: {
    width?: number | null;
    depth?: number | null;
  };
  /**
   * Where this package is offered at all. Empty means every room.
   */
  compatibleRoomTypes?:
    ('office' | 'classroom' | 'conference' | 'kitchen' | 'restroom' | 'lounge' | 'hallway' | 'other')[] | null;
  /**
   * Where it is offered first. In these rooms it appears under "Recommended", above everything else — it does not change where the package can go.
   */
  recommendedFor?:
    ('office' | 'classroom' | 'conference' | 'kitchen' | 'restroom' | 'lounge' | 'hallway' | 'other')[] | null;
  compatibleLines?: (number | BuildingLine)[] | null;
  regions?: (number | Region)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Quote requests submitted from the configurator.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  title?: string | null;
  status?: ('new' | 'forwarded' | 'webhook-failed') | null;
  contact?: {
    name?: string | null;
    email?: string | null;
    phone?: string | null;
    company?: string | null;
  };
  buildingModel?: (number | null) | BuildingModel;
  /**
   * Full QuoteConfiguration payload as submitted by the configurator.
   */
  configuration:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'regions';
        value: number | Region;
      } | null)
    | ({
        relationTo: 'building-lines';
        value: number | BuildingLine;
      } | null)
    | ({
        relationTo: 'building-models';
        value: number | BuildingModel;
      } | null)
    | ({
        relationTo: 'furniture-packages';
        value: number | FurniturePackage;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null)
    | ({
        relationTo: 'images';
        value: number | Image;
      } | null)
    | ({
        relationTo: 'models';
        value: number | Model;
      } | null)
    | ({
        relationTo: 'textures';
        value: number | Texture;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions_select".
 */
export interface RegionsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "building-lines_select".
 */
export interface BuildingLinesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  unitLabel?: T;
  description?: T;
  rules?:
    | T
    | {
        restroomsRequiredAt?: T;
        secondRestroomSetAt?: T;
      };
  regions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "building-models_select".
 */
export interface BuildingModelsSelect<T extends boolean = true> {
  title?: T;
  line?: T;
  unitCount?: T;
  restroomCount?: T;
  sqft?: T;
  sqm?: T;
  dimensions?: T;
  dimensionsMetric?: T;
  occupancy?: T;
  estimatedPrice?: T;
  leadTime?: T;
  model?: T;
  thumbnail?: T;
  regions?: T;
  sceneConfig?:
    | T
    | {
        camera?:
          | T
          | {
              position?:
                | T
                | {
                    x?: T;
                    y?: T;
                    z?: T;
                  };
              target?:
                | T
                | {
                    x?: T;
                    y?: T;
                    z?: T;
                  };
              fov?: T;
              minDistance?: T;
              maxDistance?: T;
              minPolarDeg?: T;
              maxPolarDeg?: T;
            };
        roofBlocks?:
          | T
          | {
              min?:
                | T
                | {
                    x?: T;
                    y?: T;
                    z?: T;
                  };
              max?:
                | T
                | {
                    x?: T;
                    y?: T;
                    z?: T;
                  };
              id?: T;
            };
        floorY?: T;
        floors?:
          | T
          | {
              key?: T;
              name?: T;
              floorY?: T;
              box?:
                | T
                | {
                    min?:
                      | T
                      | {
                          x?: T;
                          y?: T;
                          z?: T;
                        };
                    max?:
                      | T
                      | {
                          x?: T;
                          y?: T;
                          z?: T;
                        };
                  };
              id?: T;
            };
        roofModel?:
          | T
          | {
              model?: T;
              position?:
                | T
                | {
                    x?: T;
                    y?: T;
                    z?: T;
                  };
              yawDeg?: T;
              scale?: T;
            };
        hiddenNodePaths?: T;
      };
  rooms?:
    | T
    | {
        key?: T;
        name?: T;
        roomType?: T;
        areaSqFt?: T;
        areaSqM?: T;
        floorPolygon?:
          | T
          | {
              x?: T;
              z?: T;
              side?: T;
              id?: T;
            };
        zones?: T;
        shell?:
          | T
          | {
              floorY?: T;
              wallHeight?: T;
              wallThickness?: T;
              floorThickness?: T;
              ceilingThickness?: T;
              sunDirection?: T;
              sideAxes?: T;
            };
        openings?: T;
        surfaces?:
          | T
          | {
              wallInner?:
                | T
                | {
                    texture?: T;
                    tileWidth?: T;
                    tileHeight?: T;
                  };
              floor?:
                | T
                | {
                    texture?: T;
                    tileWidth?: T;
                    tileHeight?: T;
                  };
              ceiling?:
                | T
                | {
                    texture?: T;
                    tileWidth?: T;
                    tileHeight?: T;
                  };
            };
        openingModels?:
          | T
          | {
              door?:
                | T
                | {
                    model?: T;
                    fit?: T;
                    yawDeg?: T;
                    depth?: T;
                  };
              window?:
                | T
                | {
                    model?: T;
                    fit?: T;
                    yawDeg?: T;
                    depth?: T;
                  };
            };
        cameraPreset?:
          | T
          | {
              position?:
                | T
                | {
                    x?: T;
                    y?: T;
                    z?: T;
                  };
              target?:
                | T
                | {
                    x?: T;
                    y?: T;
                    z?: T;
                  };
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "furniture-packages_select".
 */
export interface FurniturePackagesSelect<T extends boolean = true> {
  title?: T;
  family?: T;
  tier?: T;
  model?: T;
  thumbnail?: T;
  price?: T;
  description?: T;
  footprint?:
    | T
    | {
        width?: T;
        depth?: T;
      };
  compatibleRoomTypes?: T;
  recommendedFor?: T;
  compatibleLines?: T;
  regions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  contact?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
        company?: T;
      };
  buildingModel?: T;
  configuration?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "images_select".
 */
export interface ImagesSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "models_select".
 */
export interface ModelsSelect<T extends boolean = true> {
  title?: T;
  meta?:
    | T
    | {
        sizeBefore?: T;
        sizeAfter?: T;
        triangles?: T;
        meshes?: T;
        materials?: T;
        textures?: T;
        bboxMin?: T;
        bboxMax?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "textures_select".
 */
export interface TexturesSelect<T extends boolean = true> {
  title?: T;
  meta?:
    | T
    | {
        width?: T;
        height?: T;
        sizeBefore?: T;
        sizeAfter?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?: T | {};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Where finished configurations are delivered.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integration-settings".
 */
export interface IntegrationSetting {
  id: number;
  /**
   * Quote requests are POSTed here as JSON. Leave empty to only store them in the Quotes collection.
   */
  webhookUrl?: string | null;
  /**
   * Extra HTTP headers sent with the webhook (e.g. an API key).
   */
  webhookHeaders?:
    | {
        key: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Also emit the configuration to the embedding page via window.postMessage (iframe integration).
   */
  enablePostMessage?: boolean | null;
  /**
   * Allowed origin for postMessage. Use the host-site origin in production.
   */
  targetOrigin?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Headings on the two questions asked before the building is shown. The choices themselves come from the catalogue.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-settings".
 */
export interface QuizSetting {
  id: number;
  /**
   * Shown above the questions. Left empty, nothing stands in its place.
   */
  logo?: (number | null) | Image;
  step1?: {
    /**
     * The small line above the question.
     */
    eyebrow?: string | null;
    title?: string | null;
    /**
     * Optional. A sentence under the question; empty shows nothing.
     */
    description?: string | null;
  };
  /**
   * The small line above this one is the building line the visitor just picked, so it is not set here.
   */
  step2?: {
    title?: string | null;
    /**
     * Optional. A sentence under the question; empty shows nothing.
     */
    description?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * How figures are shown to visitors.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "display-settings".
 */
export interface DisplaySetting {
  id: number;
  /**
   * Unit floor areas open in. A visitor can switch it for their own session, and their choice does not change this.
   */
  areaUnit: 'sqft' | 'sqm';
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integration-settings_select".
 */
export interface IntegrationSettingsSelect<T extends boolean = true> {
  webhookUrl?: T;
  webhookHeaders?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  enablePostMessage?: T;
  targetOrigin?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quiz-settings_select".
 */
export interface QuizSettingsSelect<T extends boolean = true> {
  logo?: T;
  step1?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  step2?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "display-settings_select".
 */
export interface DisplaySettingsSelect<T extends boolean = true> {
  areaUnit?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}